### ISSUE TITLE
Issue with Newsdata Archive - timeout

### ISSUE THREAD

**Issue by AmandinePingetPhD** [bytesview/python-client#2]
Hi, 

I have an issue with Newsdata Archive, all my requests to Archive results are not successful and I have the following error : 
Exception has occurred: ReadTimeout
HTTPSConnectionPool(host='newsdata.io', port=443): Read timed out. (read timeout=300)

Could you please provide some help on this issue?
Thank you,
Amandine Pinget, PhD
Lead Data Scientist, niiwaa

**Comment by arjunjain** [comment]
issue fixed
